//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bag
    {
        public int idBag { get; set; }
        public int idMerchSize { get; set; }
        public int idCheckout { get; set; }
        public int Qty { get; set; }
        public decimal TotalSum { get; set; }
    
        public virtual Checkout Checkout { get; set; }
        public virtual MerchSize MerchSize { get; set; }
    }
}
