//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Merchandise = new HashSet<Merchandise>();
        }
    
        public int idBrand { get; set; }
        public string Name { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<Merchandise> Merchandise { get; set; }
    }
}
