//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout
    {
        public Checkout()
        {
            this.Bag = new HashSet<Bag>();
            this.OrderStatus = new HashSet<OrderStatus>();
        }
    
        public int idCheckout { get; set; }
        public int idClient { get; set; }
        public System.DateTime Date { get; set; }
        public int idPickUpPoint { get; set; }
        public decimal TotalSum { get; set; }
    
        public virtual ICollection<Bag> Bag { get; set; }
        public virtual Client Client { get; set; }
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual ICollection<OrderStatus> OrderStatus { get; set; }
    }
}
