//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Address = new HashSet<Address>();
            this.PickUpPoint = new HashSet<PickUpPoint>();
        }
    
        public int idCity { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<PickUpPoint> PickUpPoint { get; set; }
    }
}
