//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAddress
    {
        public int idClientAddress { get; set; }
        public int idClient { get; set; }
        public int idAddress { get; set; }
        public System.DateTime DateChange { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Client Client { get; set; }
    }
}
