//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public Gender()
        {
            this.Client = new HashSet<Client>();
            this.Merchandise = new HashSet<Merchandise>();
        }
    
        public int idGender { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
        public virtual ICollection<Merchandise> Merchandise { get; set; }
    }
}
