//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchandise
    {
        public Merchandise()
        {
            this.MerchSize = new HashSet<MerchSize>();
            this.Wishlist = new HashSet<Wishlist>();
        }
    
        public int idMerchandise { get; set; }
        public string Name { get; set; }
        public int idBrand { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
        public int idCategory { get; set; }
        public int idGender { get; set; }
        public System.DateTime ReleaseDate { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MerchPhoto MerchPhoto { get; set; }
        public virtual ICollection<MerchSize> MerchSize { get; set; }
        public virtual ICollection<Wishlist> Wishlist { get; set; }
    }
}
