//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchPhoto
    {
        public int idMerchPhoto { get; set; }
        public byte[] Photo { get; set; }
        public int idMerchandise { get; set; }
    
        public virtual Merchandise Merchandise { get; set; }
    }
}
