//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchSize
    {
        public MerchSize()
        {
            this.Bag = new HashSet<Bag>();
        }
    
        public int idMerchSize { get; set; }
        public int idMerchandise { get; set; }
        public int idSizeGrid { get; set; }
        public int Qty { get; set; }
    
        public virtual ICollection<Bag> Bag { get; set; }
        public virtual Merchandise Merchandise { get; set; }
        public virtual SizeGrid SizeGrid { get; set; }
    }
}
