//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUpPoint
    {
        public PickUpPoint()
        {
            this.Checkout = new HashSet<Checkout>();
        }
    
        public int idPickUpPoint { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> idCity { get; set; }
    
        public virtual ICollection<Checkout> Checkout { get; set; }
        public virtual City City { get; set; }
    }
}
