//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skeleton_market.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeGrid
    {
        public SizeGrid()
        {
            this.MerchSize = new HashSet<MerchSize>();
        }
    
        public int idSizeGrid { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<MerchSize> MerchSize { get; set; }
    }
}
